// login constants
export const loginconstants = {
    LOGIN_REQUEST : "LOGIN_USER",
    LOGIN_SUCCESS : "LOGINED_USER",
    LOGIN_FAILURE : "LOGIN_USER_FAILLED"
}

// posting constants

export const postConstants = {
    FETCH_REQUEST : "FETCH_POSTS",
    FETCH_SUCCESS : "FETCH_POSTS_SUCCESS",
    FETCH_FAILURE : "FETCH_POSTS_FAILLED", 

    CREATE_REQUEST : "CREATE_POSTS",
    CREATE_SUCCESS : "CREATE_POSTS_SUCCESS",
    CREATE_FAILURE : "CREATE_POSTS_FAILLED",

    REMOVE_REQUEST : "REMOVE_POSTS",
    REMOVE_SUCCESS : "REMOVE_POSTS_SUCCESS",
    REMOVE_FAILURE : "REMOVE_POSTS_FAILLED" ,

    UPDATE_REQUEST : "UPDATE_POSTS",
    UPDATE_SUCCESS : "UPDATE_POSTS_SUCCESS",
    UPDATE_FAILURE : "UPDATE_POSTS_FAILLED"
}   

// api url

export const BASE_URL = "http://127.0.0.1:8000"

